### ISSUE TITLE
Seems a problem with huawei mapkit 2.3.0

### ISSUE THREAD

**Issue by chitgoks** [SupasinTatiyanupanwong/map-kit-android#15]
i did not check the app back then when i upgraded it

Today, i checked how it would look like in the map but no map shows up and in logcat it shows this error message

HmsMapKit_...ragment_13          E  MapsInitializer is not initialized.

**Comment by chitgoks** [comment]
Sorry. Closing this for now. might be an internal huawei issue. Ill contact them for support.

**Comment by chitgoks** [comment]
@SupasinTatiyanupanwong hi. could the issue be within the library? i never touched anything else since using this but i noticed now the maps do not get loaded because it says MapsInitializer is not initialized.

**Comment by chitgoks** [comment]
Closing this. The issue was that MapsInitialize.initialize() is required for Huawei Maps.

**Comment by SupasinTatiyanupanwong** [comment]
Hi @chitgoks ,

Thank you for reporting this. Ideally I think perhaps the library should do this for you. What do you think?

**Comment by chitgoks** [comment]
hi. i actually thought at first huawei maps should throw an exception so we would know. but then google maps does not throw any as well.

still, i think huawei maps should because they only introduced this probably last yr, but i never called that method because i never read the change log 

i also never received rejected submissions until now. they probably forced users to call it, else no map rendered.

**Comment by chitgoks** [comment]
if you can add it such that it will throw an exception if MapsInitializer is not initialized, that would be helpful.

because right now it just shows the error message in console. it doesnt crash the app

**Comment by SupasinTatiyanupanwong** [comment]
I believed Google Maps SDK also asking clients to manually call MapsInitializer.initalize if necessary as well. But, they also handle this themselves on our behalf if possible when we are using their Maps SDK. Perhaps it would be better if the lib will call the initializer under the hood.

**Comment by chitgoks** [comment]
ah i didnt know that. no wonder i didnt see any errors in google maps if it automatically handles it for us regardless. This is how i think huawei shoul have done it as well since i never check what's new, i only depend on compiler errors if there are new changes.

that will definitely help if mapkit will call MapsInitializer.initialize() under the hood.
