### ISSUE TITLE
AGP 4.1.0 error

### ISSUE THREAD

**Issue by PiotrPrus** [SupasinTatiyanupanwong/map-kit-android#3]
Hi, I got an error after upgrading to AGP version 4.1.0:
`java.lang.RuntimeException: Unable to get provider me.tatiyanupanwong.supasin.android.libraries.kits.maps.MapKitInitProvider: java.lang.IllegalStateException: Can't find supported platform, make sure to include one of the next artifacts: ':maps-amazon', ':maps-google', or ':maps-huawei'`
However, I did not change anything related to artifacts.

I have resolved the issue by adding following line to proguard rules:
`-keep public class me.tatiyanupanwong.supasin.android.libraries.kits.maps.** { *; }`

**Comment by SupasinTatiyanupanwong** [comment]
Hi! Thank you for reporting this issue.

This has already been addressed with #1. I'll make it available in the next release.

Until then, please keeping your mentioned proguard rule in the meantime.  😅

**Comment by SupasinTatiyanupanwong** [comment]
The fix is now available in version 1.2.2. 🙂
