### ISSUE TITLE
Move to Maven Central repository

### ISSUE THREAD

**Issue by MindaugasVarkalys** [SupasinTatiyanupanwong/map-kit-android#8]
Currently the project is published in JCenter repository. However, starting with Android Gradle Plugin 4.2.0 JCenter is deprecated because it became read-only. All the artifacts should be migrated to Maven Central https://developer.android.com/studio/build/jcenter-migration

**Comment by SupasinTatiyanupanwong** [comment]
I just published v2 in Maven Central a few days ago with minor breaking changes from v1; removal of deprecated APIs, and new namespace (old namespace seems to not serving me well in long run, sorry about that 😅)

If you are not using any APIs that marked as deprecated, then you could just swap to v2 artifact and reimport all import statements.
