### ISSUE TITLE
Migration to JCenter

### ISSUE THREAD

**Issue by jamesrapadmi** [SupasinTatiyanupanwong/map-kit-android#9]
I'm trying to remove JCenter, given it's now at end of life. Is there a plan to migrate away from it?

**Comment by SupasinTatiyanupanwong** [comment]
Please switch to v2 (with different artifact id and namespace, sorry about that, I had some trouble with the original namespace). 

Basically, all the public APIs are the same, without the deprecated one. You can just change the dependencies in your build script and fix all the imports related to the lib's classes, and you are good to go.
